services:
  
  api:
    container_name: oficina_api
    build: api
    volumes:
      - './api:/api'
    ports: 
      - '8000:8000'

  db:
    container_name: oficina_db
    build: db
    ports:
      - '27017:27017'